### ISSUE TITLE
运行kafka-log-appender出错

### ISSUE THREAD

**Issue by unclebob2013** [jiekechoo/log-analysis-kafka-storm-docker#1]
```json
kafka-log-appender git:(master) ✗ java -cp target/kafka-log-appender-1.0-SNAPSHOT.jar com.log.kafka.RogueApplication
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.log.kafka.RogueApplication.<clinit>(RogueApplication.java:11)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by jiekechoo** [comment]
这是一个基础性java问题，你单独运行jar包，需要把相关依赖打包进去或者单独引用依赖包。
